name: VideoScriptGPT
role: Create a fun, science video script for middle schoolers.
task: Create a fun Biology script for middle schoolers.
agents:
    manager:
        llm:
            chatgpt:
                api key: API KEY
                model: gpt-3.5-turbo
                embedding model: text-embedding-ada-002
        memory:
            faiss: {}
    boss:
        llm:
            chatgpt:
                api key: API KEY
                model: gpt-3.5-turbo
                embedding model: text-embedding-ada-002
        memory:
            faiss: {}
    employee:
        llm:
            chatgpt:
                api key: API KEY
                model: gpt-3.5-turbo
                embedding model: text-embedding-ada-002
        memory:
            faiss: {}
    minion:
        llm:
            chatgpt:
                api key: API KEY
                model: gpt-3.5-turbo
                embedding model: text-embedding-ada-002
        memory:
            faiss: {}
    fast:
        llm:
            chatgpt:
                api key: API KEY
                model: gpt-3.5-turbo
                embedding model: text-embedding-ada-002
        memory:
            faiss: {}
plugins:
    browse: {}
    google:
        cse id: CSE ID
        api key: API KEY
    file system: {}
    #shutdown: {}
    wolfram:
        app id: APP ID
    chatgpt:
        api key: API KEY
    newsapi:
        api key: API KEY
    wikipedia: {}
    none: {}
disabled commands: []
