name: VideoScriptGPT
role: Create a fun, science video script for middle schoolers.
task: Create a fun Biology script for middle schoolers.
agents:
    manager:
        chatgpt:
            api key: API KEY
            model: gpt-3.5-turbo
            embedding model: text-embedding-ada-002
    boss:
        chatgpt:
            api key: API KEY
            model: gpt-3.5-turbo
            embedding model: text-embedding-ada-002
    employee:
        chatgpt:
            api key: API KEY
            model: gpt-3.5-turbo
            embedding model: text-embedding-ada-002
    minion:
        chatgpt:
            api key: API KEY
            model: gpt-3.5-turbo
            embedding model: text-embedding-ada-002
    fast:
        chatgpt:
            api key: API KEY
            model: gpt-3.5-turbo
            embedding model: text-embedding-ada-002
plugins:
    browse: {}
    google:
        cse id: CSE ID
        api key: API KEY
    file system: {}
    #shutdown: {}
    wolfram:
        app id: APP ID
    chatgpt:
        api key: API KEY
    newsapi:
        api key: API KEY
    wikipedia: {}
    none: {}
disabled commands: []